# Generated by Django 5.2.7 on 2025-10-19 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Mã đơn')),
                ('customer_name', models.CharField(db_index=True, max_length=120, verbose_name='Tên khách hàng')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('pickup_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ lấy hàng')),
                ('pickup_lat', models.FloatField(blank=True, null=True, verbose_name='Pickup lat')),
                ('pickup_lng', models.FloatField(blank=True, null=True, verbose_name='Pickup lng')),
                ('drop_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ giao hàng')),
                ('drop_lat', models.FloatField(blank=True, null=True, verbose_name='Drop lat')),
                ('drop_lng', models.FloatField(blank=True, null=True, verbose_name='Drop lng')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('cod', models.PositiveIntegerField(default=0, verbose_name='COD (₫)')),
                ('status', models.CharField(choices=[('new', 'Mới tạo'), ('shipping', 'Đang giao'), ('done', 'Hoàn thành'), ('cancel', 'Đã hủy')], db_index=True, default='new', max_length=12, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên giao hàng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Giờ vào ca')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Giờ ra ca')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'ordering': ['-check_in'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', 'status'], name='orders_orde_assigne_6abf64_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'check_out'], name='orders_atte_employe_b03a8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('employee',), name='one_open_shift_per_employee'),
        ),
    ]
